-- Snapshot-like migration for current schema state.
-- This repo uses a dummy user_id only (no auth yet).

drop table if exists public.likes cascade;
drop table if exists public.posts cascade;

create table public.posts (
  id integer generated by default as identity primary key,
  content text not null,
  created_at timestamptz not null default now(),
  user_id uuid not null
);

create index posts_created_at_idx on public.posts (created_at desc);

create table public.likes (
  user_id uuid not null,
  post_id integer not null references public.posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint likes_user_post_unique unique (user_id, post_id)
);

-- RLS
alter table public.posts enable row level security;
alter table public.likes enable row level security;

-- Grants (anon key)
grant usage on schema public to anon;
grant select, insert, update on public.posts to anon;
grant select, insert, update, delete on public.likes to anon;

-- Policies (anon == dummy user)
create policy "posts_anon_select"
on public.posts for select
to anon
using (true);

create policy "posts_anon_insert"
on public.posts for insert
to anon
with check (true);

create policy "likes_anon_select"
on public.likes for select
to anon
using (true);

create policy "likes_anon_insert"
on public.likes for insert
to anon
with check (true);

create policy "likes_anon_update"
on public.likes for update
to anon
using (true)
with check (true);

create policy "likes_anon_delete"
on public.likes for delete
to anon
using (user_id = '11111111-1111-1111-1111-111111111111'::uuid);

